### ISSUE TITLE
Problem with HomeKit when NOT in the WLAN

### ISSUE THREAD

**Issue by Mandy2000** [SamGabbay/tesla-siri-homekit#1]
Hi Sam,
CONGRATULATIONS, GREAT job on this piece of software. During install everything worked fine for me. And everything is working when sitting in my house using my WiFi. But when leaving the status of the items changes to OFFLINE. I USE an AppleTV (3rd gen) and my Elgato Eve power plug works fine with HomeKit even when I am on the road using 3G or LTE. It still says ONLINE. Only the Energi items are OFFLINE!?
Do you have an idea what is wrong here? Is there maybe a problem or even a bug in your software?

THANKS so much for your help
Manfred

**Comment by SamGabbay** [comment]
Mandy2000,

It took an hour or two and a sign out/in to iCloud for it to fully work on the Apple TV. This is why I say that a Raspberry PI implementation is the best. I'll be doing a video and Software on that very soon.

Sam

**Comment by Mandy2000** [comment]
Hi Sam,
thanks for your fast reply. Well so I hope to see the video soon. As I am not really good in programming and computing I please need an explanation “for Dummys” ;)
The video for the setup on the Mac was by the way GREAT. Except for the part with the AppleTV everything was clearly explained and easy understandable. Thanks for this perfect tutorial.

all the best
Manfred

**Comment by Mandy2000** [comment]
Hi Sam,
just one short information. As I own an AppleTV 3rd gen, I just tested with the AppleTV 4th gen of my neighbor. It IMMEDIATELY worked ... So there really might be a problem with the 3rd gen, which many people confirmed on different websites on the internet ...

**Comment by SamGabbay** [comment]
Mandy,

You are 100% Correct. It would not work on my Father-in-laws 3rd Generation Apple TV but works on my 4th Generation!
